### ISSUE TITLE
Unable to auto reconnect

### ISSUE THREAD

**Issue by nicman23** [DanielOgorchock/linux#23]
to reconnect my switch pro controller i need to long press the small button and manually connect from the pc.

not sure if userland or this module issue but a ps3 controller i also have does not exhibit the issue

also
https://github.com/nicman23/dkms-hid-nintendo/issues/39

**Comment by Rodancoci** [comment]
I have the same issue. Once the controller is off (either from being manually turned off or from ramdom disconnections) I have to pair it again for it to work.

**Comment by nicman23** [comment]
works on latest dkms and joycond git, closing
