### ISSUE TITLE
Cam

### ISSUE THREAD

**Issue by Izhanm11** [DanielOgorchock/linux#47]

**Comment by Izhanm11** [comment]
sorry for the previous comment, accidentally pressed enter.
I can't install this on fedora 37. I tried all of the commands but it just won't work. How do I install this on Fedora?

**Comment by SuperSamus** [comment]
hid-nintendo has been included in the Linux kernel since 5.16. Fedora 37's kernel version is way beyond that. You shouldn't need to do anything.

(Also, you can edit comments, you didn't need to create a new one)

**Comment by Izhanm11** [comment]
thanks

**Comment by SuperSamus** [comment]
Close the issue if solved.
